x-spark-common: &spark-common
  image: bitnami/spark:3.5.1
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
    - ./mnt/checkpoints:/mnt/spark-checkpoints
    - ./mnt/spark-state:/mnt/spark-state
  networks:
    - michal

x-kafka-controller-base: &kafka-controller-base
  image: apache/kafka:3.8.1
  restart: on-failure
  command:
    - /bin/sh
    - -c
    - |
      echo '
      log4j.rootLogger=INFO, stdout, kafkaAppender

      # Configure stdout appender
      log4j.appender.stdout=org.apache.log4j.ConsoleAppender
      log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
      log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n

      # Configure kafka file appender
      log4j.appender.kafkaAppender=org.apache.log4j.RollingFileAppender
      log4j.appender.kafkaAppender.File=/opt/kafka/logs/kafka.log
      log4j.appender.kafkaAppender.MaxFileSize=10MB
      log4j.appender.kafkaAppender.MaxBackupIndex=10
      log4j.appender.kafkaAppender.layout=org.apache.log4j.PatternLayout
      log4j.appender.kafkaAppender.layout.ConversionPattern=[%d] %p %m (%c)%n
      ' > tmp/log4j.properties
      /etc/kafka/docker/run
  volumes:
    - ./volumes/jmx_exporter:/usr/share/jmx_exporter
  networks:
    - michal

x-kafka-controller-env: &kafka-controller-env
  KAFKA_PROCESS_ROLES: controller
  KAFKA_LISTENERS: CONTROLLER://:9093
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
  KAFKA_CLUSTER_ID: 5L6g3nSht-eMCtk--X86sw
  KAFKA_LOG4J_OPTS: -Dlog4j.configuration=file:/tmp/log4j.properties

services:
  kafka-controller:
    <<: *kafka-controller-base
    container_name: kafka-controller-1
    environment:
      <<: *kafka-controller-env
      KAFKA_NODE_ID: 1
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/tmp/log4j.properties"
      KAFKA_OPTS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.16.1.jar=9300:/usr/share/jmx_exporter/kafka-broker.yml"
    networks:
      - michal
    volumes:
      - ./volumes/controller_data_1:/var/lib/kafka/data
      - ./logs/controller-logs_1:/opt/kafka/logs
      - ./volumes/jmx_exporter:/usr/share/jmx_exporter/
  kafka-controller-2:
    <<: *kafka-controller-base
    container_name: kafka-controller-2
    environment:
      <<: *kafka-controller-env
      KAFKA_NODE_ID: 2
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/tmp/log4j.properties"
      KAFKA_OPTS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.16.1.jar=9300:/usr/share/jmx_exporter/kafka-broker.yml"
    networks:
      - michal
    volumes:
      - ./volumes/controller_data_2:/var/lib/kafka/data
      - ./logs/controller-logs_2:/opt/kafka/logs
      - ./volumes/jmx_exporter:/usr/share/jmx_exporter/
  kafka-controller-3:
    <<: *kafka-controller-base
    container_name: kafka-controller-3
    environment:
      <<: *kafka-controller-env
      KAFKA_NODE_ID: 3
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/tmp/log4j.properties"
      KAFKA_OPTS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.16.1.jar=9300:/usr/share/jmx_exporter/kafka-broker.yml"
    networks:
      - michal
    volumes:
      - ./volumes/controller_data_3:/var/lib/kafka/data
      - ./logs/controller-logs_3:/opt/kafka/logs
      - ./volumes/jmx_exporter:/usr/share/jmx_exporter/

  kafka-broker:
    image: apache/kafka:3.8.1
    restart: on-failure
    container_name: kafka-broker-1
    command:
      - /bin/sh
      - -c
      - |
        echo '
        log4j.rootLogger=INFO, stdout, kafkaAppender

        # Configure stdout appender
        log4j.appender.stdout=org.apache.log4j.ConsoleAppender
        log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
        log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n

        # Configure kafka file appender
        log4j.appender.kafkaAppender=org.apache.log4j.RollingFileAppender
        log4j.appender.kafkaAppender.File=/opt/kafka/logs/kafka.log
        log4j.appender.kafkaAppender.MaxFileSize=10MB
        log4j.appender.kafkaAppender.MaxBackupIndex=10
        log4j.appender.kafkaAppender.layout=org.apache.log4j.PatternLayout
        log4j.appender.kafkaAppender.layout.ConversionPattern=[%d] %p %m (%c)%n
        ' > tmp/log4j.properties
        /etc/kafka/docker/run
    ports:
      - "29092:9092"
    environment:
      KAFKA_CLUSTER_ID: 5L6g3nSht-eMCtk--X86sw
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-1:19092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9094,3@kafka-controller-3:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/tmp/log4j.properties"
      KAFKA_OPTS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.16.1.jar=9300:/usr/share/jmx_exporter/kafka-broker.yml"
    networks:
      - michal
    volumes:
      - ./volumes/broker_data_1:/var/lib/kafka/data
      - ./logs/broker-logs_1:/opt/kafka/logs
      - ./volumes/jmx_exporter:/usr/share/jmx_exporter/
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - kafka-controller
      - kafka-controller-2
      - kafka-controller-3
  kafka-broker-2:
    image: apache/kafka:3.8.1
    restart: on-failure
    container_name: kafka-broker-2
    command:
      - /bin/sh
      - -c
      - |
        echo '
        log4j.rootLogger=INFO, stdout, kafkaAppender

        # Configure stdout appender
        log4j.appender.stdout=org.apache.log4j.ConsoleAppender
        log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
        log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n

        # Configure kafka file appender
        log4j.appender.kafkaAppender=org.apache.log4j.RollingFileAppender
        log4j.appender.kafkaAppender.File=/opt/kafka/logs/kafka.log
        log4j.appender.kafkaAppender.MaxFileSize=10MB
        log4j.appender.kafkaAppender.MaxBackupIndex=10
        log4j.appender.kafkaAppender.layout=org.apache.log4j.PatternLayout
        log4j.appender.kafkaAppender.layout.ConversionPattern=[%d] %p %m (%c)%n
        ' > tmp/log4j.properties
        /etc/kafka/docker/run
    ports:
      - "39092:9092"
    environment:
      KAFKA_CLUSTER_ID: 5L6g3nSht-eMCtk--X86sw
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-2:19092,PLAINTEXT_HOST://localhost:39092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9094,3@kafka-controller-3:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/tmp/log4j.properties"
      KAFKA_OPTS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.16.1.jar=9300:/usr/share/jmx_exporter/kafka-broker.yml"
    networks:
      - michal
    volumes:
      - ./volumes/broker_data_2:/var/lib/kafka/data
      - ./logs/broker-logs_2:/opt/kafka/logs
      - ./volumes/jmx_exporter:/usr/share/jmx_exporter/
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - kafka-controller
      - kafka-controller-2
      - kafka-controller-3
  kafka-broker-3:
    image: apache/kafka:3.8.1
    restart: on-failure
    container_name: kafka-broker-3
    command:
      - /bin/sh
      - -c
      - |
        echo '
        log4j.rootLogger=INFO, stdout, kafkaAppender

        # Configure stdout appender
        log4j.appender.stdout=org.apache.log4j.ConsoleAppender
        log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
        log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n

        # Configure kafka file appender
        log4j.appender.kafkaAppender=org.apache.log4j.RollingFileAppender
        log4j.appender.kafkaAppender.File=/opt/kafka/logs/kafka.log
        log4j.appender.kafkaAppender.MaxFileSize=10MB
        log4j.appender.kafkaAppender.MaxBackupIndex=10
        log4j.appender.kafkaAppender.layout=org.apache.log4j.PatternLayout
        log4j.appender.kafkaAppender.layout.ConversionPattern=[%d] %p %m (%c)%n
        ' > tmp/log4j.properties
        /etc/kafka/docker/run
    ports:
      - "49092:9092"
    environment:
      KAFKA_CLUSTER_ID: 5L6g3nSht-eMCtk--X86sw
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-3:19092,PLAINTEXT_HOST://localhost:49092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9094,3@kafka-controller-3:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/tmp/log4j.properties"
      KAFKA_OPTS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.16.1.jar=9300:/usr/share/jmx_exporter/kafka-broker.yml"
    networks:
      - michal
    volumes:
      - ./volumes/broker_data_3:/var/lib/kafka/data
      - ./logs/broker-logs_3:/opt/kafka/logs
      - ./volumes/jmx_exporter:/usr/share/jmx_exporter/
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - kafka-controller
      - kafka-controller-2
      - kafka-controller-3
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.1
    container_name: schema-registry
    healthcheck:
      test: curl --fail http://localhost:18081/subjects || exit 1
      interval: 5s
      retries: 10
      start_period: 5s
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker-1:19092,PLAINTEXT://kafka-broker-2:19092,PLAINTEXT://kafka-broker-3:19092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:18081
    ports:
      - "18081:8081"
    depends_on:
      - kafka-broker
      - kafka-broker-2
      - kafka-broker-3
    networks:
      - michal
  redpanda:
    image: docker.redpanda.com/redpandadata/console:v2.5.2
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka-broker-1:19092", "kafka-broker-2:19092", "kafka-broker-3:19092"]
          schemaRegistry:
            enabled: true
            urls: ["http://schema-registry:18081"]
        redpanda:
          adminApi:
            enabled: false
            urls: ["http://redpanda:9644"]
    ports:
      - "8080:8080"
    depends_on:
      schema-registry:
        condition: service_healthy
    networks:
      - michal
  spark-master:
    <<: *spark-common
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    ports:
      - "9190:8080"
      - "7077:7077"
      - "4040:4040"
      - "8081:8081"
  spark-worker: &spark-worker-image
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
  spark-worker-2:
    <<: *spark-worker-image
  spark-worker-3:
    <<: *spark-worker-image
  java-producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-producer
    environment:
      KAFKA_BROKERS: "kafka-broker-1:19092,kafka-broker-2:19092,kafka-broker-3:19092"
    networks:
      - michal
    depends_on:
      - kafka-broker
      - kafka-broker-2
      - kafka-broker-3
  prometheus:
    image: prom/prometheus:v3.0.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
    networks:
      - michal
    depends_on:
      - kafka-broker
      - kafka-broker-2
      - kafka-broker-3
      - spark-master
      - spark-worker
      - spark-worker-2
      - spark-worker-3

  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports:
      - "59093:9093"
    networks:
      - michal

networks:
  michal:
volumes:
  controller_data_1:
  controller_data_2:
  controller_data_3:
  broker_data_1:
  broker_data_2:
  broker_data_3:


