groups:
- name: Kafka Alerts
  rules:
  - alert: KafkaHighRequestLatency
    expr: kafka_request_altency_ms > 100
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High request latency detected"
      description: "Kafka request latency is above 100ms for more than 1 minute."