global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 15s

rule_files: ["rules/alert_rules.yml"]

alerting:
  alertmanagers:
    - timeout: "10s"
      scheme: http
      static_configs:
        - targets: ['alertmanager:59093']

scrape_configs:
  - job_name: kafka-controllers
    scrape_interval: 15s
    scrape_timeout: 15s
    scheme: http
    static_configs:
      - targets:
          - kafka-controller-1:9300
          - kafka-controller-2:9300
          - kafka-controller-3:9300

  - job_name: kafka-brokers
    scrape_interval: 15s
    scrape_timeout: 15s
    scheme: http
    static_configs:
      - targets:
          - kafka-broker-1:9300
          - kafka-broker-2:9300
          - kafka-broker-3:9300

  
